on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.4.4
        with:
          version: 10.x
      - uses: actions/cache@v2
        with:
          path: node_modules
          id: cache
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-
      - name: Install package
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm i
      - name: Set env
        id: file
        run: echo ::set-output name=name::frontend-${GITHUB_REF#refs/*/}.zip
      - name: Build project
        run: |
          echo 'VUE_APP_API_ROOT=http://localhost:5000' > .env.local
          npm run build
          zip -r ${{ steps.file.outputs.name }} dist/
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ contains(github.ref, '-') }}
          files: |
            ${{ steps.file.outputs.name }}
